# query_voice_root/agentic_pipeline/final_validation_test.py
import sqlite3
import pandas as pd
import os
from graph import create_graph, load_local_llm

def get_truth_value(query, db_path):
    conn = sqlite3.connect(db_path)
    res = pd.read_sql_query(query, conn)
    conn.close()
    if res.empty:
        return None
    return res.iloc[0, 0]

def run_validation():
    print("--- [INITIALIZING VALIDATION SUITE] ---")
    llm = load_local_llm()
    app = create_graph(llm)
    
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DB_PATH = os.path.join(BASE_DIR, "data_engineering", "queryvoice_local.db")

    test_cases = [
        {
            "question": "What is the total revenue for the 'Consulting Hours' category?",
            "truth_sql": "SELECT SUM(f.revenue) FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id WHERE p.category = 'Consulting Hours'"
        },
        {
            "question": "Which country has the highest total profit from 'SaaS Subscription'?",
            "truth_sql": "SELECT u.country FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id JOIN dim_users u ON f.user_id = u.user_id WHERE p.category = 'SaaS Subscription' GROUP BY u.country ORDER BY SUM(f.profit) DESC LIMIT 1"
        },
        {
            "question": "How many premium users do we have in Spain?",
            "truth_sql": "SELECT COUNT(*) FROM dim_users WHERE country = 'Spain' AND is_premium = 1"
        },
        {
            "question": "What is the total profit generated by products costing more than $1000 last month?",
            "truth_sql": "SELECT SUM(f.profit) FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id WHERE p.unit_price > 1000 AND f.sale_timestamp >= date('now', '-1 month')"
        },
        {
            "question": "Who is the top user by revenue in the 'Add-on Feature' category?",
            "truth_sql": "SELECT u.name FROM fact_sales f JOIN dim_users u ON f.user_id = u.user_id JOIN dim_products p ON f.product_id = p.product_id WHERE p.category = 'Add-on Feature' GROUP BY u.name ORDER BY SUM(f.revenue) DESC LIMIT 1"
        }
    ]

    print(f"\n--- [STARTING GROUND TRUTH VALIDATION] ---\n")

    for i, test in enumerate(test_cases):
        print(f"-------------------------------------------------------")
        print(f"QUESTION {i+1}: {test['question']}")
        
        # 1. Run AI Pipeline
        inputs = {"raw_voice_input": test["question"], "retry_count": 0}
        final_state = app.invoke(inputs)
        
        ai_summary = final_state.get("final_answer", "N/A")
        ai_raw_res = final_state.get("execution_result")
        retries = final_state.get("retry_count", 0)
        
        # Extract raw value from AI result for comparison
        ai_val = None
        if ai_raw_res:
            df_ai = pd.DataFrame(ai_raw_res)
            if not df_ai.empty:
                ai_val = df_ai.iloc[0, 0]

        # 2. Run Manual Truth
        truth_val = get_truth_value(test["truth_sql"], DB_PATH)

        # 3. Compare
        # 3. Compare
        status = "MATCH [OK]"
        # Handle float comparison and string comparison
        if str(ai_val) != str(truth_val):
            try:
                # Use small epsilon for float comparison
                if abs(float(ai_val) - float(truth_val)) > 0.01:
                    status = "MISMATCH [ERROR]"
            except:
                status = "MISMATCH [ERROR]"

        print(f"AI RESULT:    {ai_summary}")
        print(f"RAW AI VAL:   {ai_val}")
        print(f"MANUAL TRUTH: {truth_val}")
        print(f"RETRIES:      {retries}")
        print(f"STATUS:       {status}")
        
    print(f"-------------------------------------------------------")
    print(f"\n--- [VALIDATION COMPLETE] ---")

if __name__ == "__main__":
    run_validation()
