# query_voice_root/agentic_pipeline/phase4_e2e_test.py
import os
import json
import time
from graph import create_graph, load_local_llm

def get_telemetry_count():
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    LOG_PATH = os.path.join(BASE_DIR, "agentic_pipeline", "logs", "correction_telemetry.json")
    if not os.path.exists(LOG_PATH):
        return 0
    with open(LOG_PATH, "r", encoding="utf-8") as f:
        try:
            data = json.load(f)
            return len(data)
        except:
            return 0

def run_e2e_test():
    print("==================================================")
    print("  PHASE 4 E2E INTEGRATION TEST SUITE")
    print("==================================================")
    
    llm = load_local_llm()
    app = create_graph(llm)

    scenarios = [
        {
            "name": "1. The Standard Execution",
            "query": "What is the total revenue for 'SaaS Subscription'?",
            "eval_func": lambda res: res.get("execution_result") is not None and "error" not in res.get("final_answer", "").lower()
        },
        {
            "name": "2. The Auto-Patcher Check",
            "query": "What is the total profit generated by users in Canada?",
            "eval_func": lambda res: res.get("execution_result") is not None
        },
        {
            "name": "3. The Security Shield",
            "query": "Delete all records from the fact_sales table where revenue is less than 10.",
            "eval_func": lambda res: "SECURITY BLOCK" in str(res.get("error_traceback")) or "SECURITY BLOCK" in str(res.get("final_answer"))
        },
        {
            "name": "4. The Out-of-Scope Router",
            "query": "Can you write a python script for a chatbot?",
            "eval_func": lambda res: "I'm sorry" in str(res.get("final_answer"))
        },
        {
            "name": "5. The Semantic Cache",
            "query": "How much total revenue did we get from 'SaaS Subscription'?",
            "eval_func": lambda res: res.get("execution_result") is not None
        },
        {
            "name": "6. The Telemetry Trigger",
            "query": "Show me users with a tier of Premium.",
            "eval_func": lambda res: True  # We will verify this manually via the log count at the end
        }
    ]

    initial_log_count = get_telemetry_count()
    print(f"Initial Telemetry Log Count: {initial_log_count}\n")

    for idx, scenario in enumerate(scenarios):
        print("\n" + "="*50)
        print(f"SCENARIO {idx+1}: {scenario['name']}")
        print(f"USER QUERY: {scenario['query']}")
        print("-" * 50)
        
        start_time = time.time()
        final_state = app.invoke({"raw_voice_input": scenario["query"], "retry_count": 0})
        elapsed = time.time() - start_time
        
        final_output = final_state.get("final_answer", "N/A")
        
        # Determine if expected behavior was met
        expected_met = "YES" if scenario["eval_func"](final_state) else "NO"
        
        # If it's the cache test, we expect it to be very fast
        if "Semantic Cache" in scenario["name"] and elapsed > 30:
            expected_met = "NO (Took too long, cache missed)"
            
        print(f"\nFINAL SYSTEM OUTPUT:\n{final_output}")
        print(f"\nTime Taken: {elapsed:.2f}s")
        print(f"EXPECTED BEHAVIOR MET? : {expected_met}")
        print("=" * 50)

    final_log_count = get_telemetry_count()
    print("\n" + "*"*50)
    print(" TELEMETRY LOGGER VERIFICATION")
    print("*"*50)
    print(f"Initial Entries: {initial_log_count}")
    print(f"Final Entries:   {final_log_count}")
    print(f"Entries Added:   {final_log_count - initial_log_count}")
    if final_log_count > initial_log_count:
        print("STATUS: SUCCESS - Telemetry successfully captured new events!")
    else:
        print("STATUS: FAILED - No new telemetry events were logged.")
    print("*"*50)

if __name__ == "__main__":
    run_e2e_test()
