# query_voice_root/agentic_pipeline/stress_test.py
# Boundary Stress Test: Validates that the SQL Auto-Patcher ONLY triggers
# for profit queries and leaves revenue/quantity queries intact.
import sqlite3
import pandas as pd
import os
from graph import create_graph, load_local_llm

def get_truth_value(query, db_path):
    conn = sqlite3.connect(db_path)
    res = pd.read_sql_query(query, conn)
    conn.close()
    if res.empty:
        return None
    return res.iloc[0, 0]

def run_stress_test():
    print("--- [INITIALIZING BOUNDARY STRESS TEST] ---")
    llm = load_local_llm()
    app = create_graph(llm)

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DB_PATH = os.path.join(BASE_DIR, "data_engineering", "queryvoice_local.db")

    test_cases = [
        {
            "question": "What is the total revenue for the 'Enterprise License' category?",
            "truth_sql": "SELECT SUM(f.revenue) FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id WHERE p.category = 'Enterprise License'",
            "expect_patcher": False
        },
        {
            "question": "What is the total profit generated by users from Morocco?",
            "truth_sql": "SELECT SUM(f.profit) FROM fact_sales f JOIN dim_users u ON f.user_id = u.user_id WHERE u.country = 'Morocco'",
            "expect_patcher": True
        },
        {
            "question": "What is the total revenue generated by the top 3 most expensive products?",
            "truth_sql": "SELECT SUM(f.revenue) FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id WHERE p.product_id IN (SELECT product_id FROM dim_products ORDER BY unit_price DESC LIMIT 3)",
            "expect_patcher": False
        },
        {
            "question": "Which category generated the least profit overall?",
            "truth_sql": "SELECT p.category FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id GROUP BY p.category ORDER BY SUM(f.profit) ASC LIMIT 1",
            "expect_patcher": True
        },
        {
            "question": "What is the total quantity of 'Consulting Hours' sold to Premium users?",
            "truth_sql": "SELECT SUM(f.quantity) FROM fact_sales f JOIN dim_products p ON f.product_id = p.product_id JOIN dim_users u ON f.user_id = u.user_id WHERE p.category = 'Consulting Hours' AND u.is_premium = 1",
            "expect_patcher": False
        }
    ]

    print(f"\n--- [STARTING BOUNDARY STRESS TEST] ---\n")

    match_count = 0
    for i, test in enumerate(test_cases):
        print(f"-------------------------------------------------------")
        patcher_label = "[PATCHER EXPECTED]" if test["expect_patcher"] else "[NO PATCHER]"
        print(f"QUESTION {i+1} {patcher_label}: {test['question']}")

        # 1. Run AI Pipeline
        inputs = {"raw_voice_input": test["question"], "retry_count": 0}
        final_state = app.invoke(inputs)

        ai_summary = final_state.get("final_answer", "N/A")
        ai_raw_res = final_state.get("execution_result")
        retries = final_state.get("retry_count", 0)

        # Extract raw value from AI result
        ai_val = None
        if ai_raw_res:
            df_ai = pd.DataFrame(ai_raw_res)
            if not df_ai.empty:
                ai_val = df_ai.iloc[0, 0]

        # 2. Run Manual Truth
        truth_val = get_truth_value(test["truth_sql"], DB_PATH)

        # 3. Compare
        status = "MATCH [OK]"
        if str(ai_val) != str(truth_val):
            try:
                if abs(float(ai_val) - float(truth_val)) > 0.01:
                    status = "MISMATCH [ERROR]"
            except:
                status = "MISMATCH [ERROR]"

        if status == "MATCH [OK]":
            match_count += 1

        print(f"AI RESULT:    {ai_summary}")
        print(f"RAW AI VAL:   {ai_val}")
        print(f"MANUAL TRUTH: {truth_val}")
        print(f"RETRIES:      {retries}")
        print(f"STATUS:       {status}")

    print(f"-------------------------------------------------------")
    print(f"\n--- [STRESS TEST COMPLETE] ---")
    print(f"SCORE: {match_count}/5")

if __name__ == "__main__":
    run_stress_test()
